### ISSUE TITLE
[Process] Background processing

### ISSUE THREAD

**Issue by moovida** [Polymap4/polymap4-p4#141]
Background processing is a mandatory feature, since the power of using the web here could be to launch the process before leaving from work, check it out at home just to have an idea if it is working and then checkout the results the following 1-2-3-X days when the process is done. For this ideas are:

  - [x] background process monitor is necessary
  - [ ] outputs can't be as they are now. It is mandatory to be able to define them before launching the module. The process could be done but I might access it after a week. So it should have written things to disk
  - [ ] a plus would be the possibility to send an email or some kind of notification when the process is done, both on finish or error

### TODO

  - [x] progress in concurrent sessions
  - [x] update UI when job state changes (in other session)
  - [x] remove job after completion (UI update in concurrent sessions)
  - [ ] prevent mapzone controller to stop instance while process is running

**Comment by fb71** [comment]
The current processing model/API allows for multiple consumers to handle (the same) output data types. Moreover, the user can switch between different consumers. For example, first have a look at the produced map, and then make a new layer out of the produced data. This would not be possible if the UI forces the user to define consumer beforehand.

And, it is not necessary at all. IMO we can perfectly stay with the current model. We just need a queue of running processes and a way to restore the UI from a running process. This way the user could check progress at any time. Once a process ends the user is informed, online in the UI or offline per email (?). The user then opens the finished process and can use the results view/UI just like today.

Raster results consume **a lot** of memory. In order to compute multiple processes over days it would be very important to have (Memory-mapped raster backend)[http://github.com/moovida/jgrasstools/issues/37] or something in place in order to keep memory usage under control.
