### ISSUE TITLE
[Import] WFS 

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-p4#145]
Current WFS import seem to be unstable. Plus, for Atlas we need cached features.

### TODO

  - [x] Catalog -> direct WFS access
  - [x] periodic sync -> internal store
  - [x] NewLayerOperation concerns
  - [x] Duplicate entries after operation
  - [x] Statistics
  - [x] Clear cache button
  - [x] No capabilities documents after GeoTools upgrade

### Refresh after pipeline change

  - [x] WMS styles param handling (Map refresh) 
  - [ ] zIndex after re-add on style change
  - [x] Reload FeatureLayer: ??? (FeatureTable refresh)
  - [ ] ETag (actual 304) (Map refresh)

### Tile cache

  - [x] Cache304 expired tiles

**Comment by fb71** [comment]
java.util.concurrent.ExecutionException: org.polymap.core.data.pipeline.PipelineBuilderException: java.lang.IllegalStateException: Name already loaded: atlas:kinderbetreuungseinrichtungen
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.polymap.p4.layer.LayersPanel$LayerActiveAction.update(LayersPanel.java:397)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:155)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:935)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:103)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:52)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1015)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:483)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:52)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2151)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:830)
	at org.eclipse.jface.viewers.AbstractTreeViewer$1.run(AbstractTreeViewer.java:805)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:66)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:779)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:644)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:750)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalInitializeTree(AbstractTreeViewer.java:1495)
	at org.eclipse.jface.viewers.TreeViewer.internalInitializeTree(TreeViewer.java:833)
	at org.eclipse.jface.viewers.AbstractTreeViewer$5.run(AbstractTreeViewer.java:1479)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1427)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:403)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1388)
	at org.eclipse.jface.viewers.AbstractTreeViewer.inputChanged(AbstractTreeViewer.java:1472)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:280)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1674)
	at org.polymap.p4.layer.LayersPanel.createContents(LayersPanel.java:186)
	at org.polymap.p4.layer.LayersCatalogsPanel.createLayersContents(LayersCatalogsPanel.java:175)
	at org.polymap.p4.layer.LayersCatalogsPanel.createContents(LayersCatalogsPanel.java:154)
	at org.polymap.rhei.batik.engine.DefaultAppDesign.createPanelContents(DefaultAppDesign.java:318)
	at org.polymap.rhei.batik.engine.DefaultAppDesign.panelChanged(DefaultAppDesign.java:521)
	at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.polymap.core.runtime.event.AnnotatedEventListener$DeferredAnnotatedMethod.handleEvent(AnnotatedEventListener.java:244)
	at org.polymap.core.runtime.event.DisplayingListener$1.run(DisplayingListener.java:58)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:180)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1196)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.polymap.rhei.batik.BatikApplication.createUI(BatikApplication.java:163)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:172)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:284)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:105)
Caused by: org.polymap.core.data.pipeline.PipelineBuilderException: java.lang.IllegalStateException: Name already loaded: atlas:kinderbetreuungseinrichtungen
	at org.polymap.core.data.pipeline.PipelineBuilderBase.createPipeline(PipelineBuilderBase.java:42)
	at org.polymap.core.data.pipeline.AutoWirePipelineBuilder.createPipeline(AutoWirePipelineBuilder.java:158)
	at org.polymap.p4.data.P4PipelineBuilder.createPipeline(P4PipelineBuilder.java:98)
	at org.polymap.p4.layer.FeatureLayer.doConnectLayer(FeatureLayer.java:190)
	at org.polymap.p4.layer.FeatureLayer.lambda$4(FeatureLayer.java:118)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.polymap.p4.layer.FeatureLayer.lambda$0(FeatureLayer.java:115)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at org.polymap.core.runtime.JobExecutor$2.runWithException(JobExecutor.java:103)
	at org.polymap.core.runtime.UIJob.lambda$0(UIJob.java:232)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
	at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
	at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
	at org.polymap.core.runtime.UIJob.run(UIJob.java:228)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Name already loaded: atlas:kinderbetreuungseinrichtungen
	at org.polymap.core.data.rs.RDataStore.getNames(RDataStore.java:188)
	at org.polymap.core.data.feature.storecache.FullDataStoreSyncStrategy.beforeInit(FullDataStoreSyncStrategy.java:74)
	at org.polymap.core.data.feature.storecache.StoreCacheProcessor.init(StoreCacheProcessor.java:141)
	at org.polymap.core.data.pipeline.PipelineBuilderBase.createPipeline(PipelineBuilderBase.java:38)
	... 15 more
Caused by: java.lang.IllegalStateException: Name already loaded: atlas:kinderbetreuungseinrichtungen
	at org.polymap.core.data.rs.RDataStore.getNames(RDataStore.java:182)
	... 18 more
