### ISSUE TITLE
Layer & Catalog UI

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-p4#146]
## Problems / issues

  - its hard to get the idea whats a layer and whats the catalog
  - ...

## TODO

  - [x] no top-level catalog panel
  - Catalog list
    - [x] no catalogs level
    - [/] white open background
    - [x] no click on DataSource
    - [x] "open" chevron for resources?
    - [ ] delete entry/service?
    - [x] Data preview
  - [ ] Catalog has no scrollbar / sash child sizes
  - [x] Auge eckig
  - [x] Layer "open" chevron?
  - [x] Up/Down drag&drop

**Comment by fb71** [comment]
This issue was about the idea to have no Catalog panel and at all, but integrating Layers and the Catalog in one panel. This is better but does not work out really well either. Anyway, we have been using this solution for quite some time. I'm gonna close this and open a new one (#147) for the next round of development.
