### ISSUE TITLE
Layer&Catalog: Tabs

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-p4#147]
The next round (#146) of this tough undertaking. The idea now is to use Tabs to have layers and catalog side-by-side but on the other hand give them more space and a cleaner UX.

#### Problems
  - Where does a service actually come from?
  - What service/resource a layer is actually connected with?

#### Todo
  - [ ] Tabs for Layers and Catalog
  - [ ] Info dialog on first use / layer click (?)
  - [ ] Catalog Search
  - [ ] Catalog: second line: Type and URL + Info action for more info

  - [ ] ResourcePanel: Section sequence + unexpanded preview sections (?)
  - [ ] Image cache on map preview
